/**
 * Client-side Document Exporter for Iroko AI.
 *
 * Uses the official `docx` library (via Packer.toBlob) to generate native
 * Microsoft Word (.docx) files — real Office Open XML, not HTML-in-.doc.
 *
 * Falls back to the server endpoint `/api/generate-document/docx` when
 * client-side Packer is unavailable (e.g. very old browsers, SSR context).
 *
 * PDF uses the browser's native print-to-PDF engine via window.open().
 */

import {
  Document,
  Packer,
  Paragraph,
  TextRun,
  AlignmentType,
  HeadingLevel,
  BorderStyle,
  UnderlineType,
} from 'docx'

/* ------------------------------------------------------------------ */
/*  Detection helpers                                                  */
/* ------------------------------------------------------------------ */

/** Check if text content is a formal legal document, contract, or formal letter. */
export function isLegalDocument(text: string): boolean {
  if (!text || text.length < 150) return false

  // 1. Explicit document heading (# TENANCY AGREEMENT, # DEMAND NOTICE, etc.)
  const hasDocHeading =
    /^#\s+.*(agreement|contract|letter|notice|memorandum|resolution|deed|invoice|affidavit|declaration|demand)/im.test(
      text,
    )
  if (hasDocHeading) return true

  // 2. Formal letter structure (works with real names, not just [placeholders])
  const hasLetterStructure =
    (text.includes('Dear ') ||
      text.includes('RE:') ||
      text.includes('Subject:')) &&
    (text.includes('Yours faithfully') ||
      text.includes('Yours sincerely') ||
      text.includes('Yours truly'))
  if (hasLetterStructure) return true

  // 3. Formal contract / legal agreement structural elements
  const lower = text.toLowerCase()
  const contractKeywords = [
    'in witness whereof',
    'now it is hereby agreed',
    'terms and conditions',
    'whereas the',
    'hereinafter',
    'this agreement is made',
  ]
  const matchCount = contractKeywords.filter((k) => lower.includes(k)).length
  if (matchCount >= 2) return true

  return false
}

/** Extract document title from markdown heading or first line. */
export function extractDocTitle(text: string): string {
  const match = text.match(/^#\s+(.+)$/m)
  if (match?.[1]) {
    return match[1].replace(/[*_#]/g, '').trim()
  }

  const letterSubj = text.match(/(?:Subject|RE):\s*(.+)$/im)
  if (letterSubj?.[1]) {
    return letterSubj[1]
      .replace(/[*_#]/g, '')
      .trim()
      .slice(0, 50)
  }

  const lines = text.split('\n').filter((l) => l.trim().length > 0)
  if (lines[0]) {
    return lines[0]
      .replace(/[*_#]/g, '')
      .trim()
      .slice(0, 50)
  }
  return 'Iroko_Document'
}

/**
 * Strip the Iroko AI disclaimer and trailing HR separator from text
 * before exporting to Word/PDF. The disclaimer is visible in chat
 * but should NOT appear in the downloadable document.
 */
export function stripDisclaimerForExport(text: string): string {
  let cleaned = text

  // Remove the Iroko AI disclaimer paragraph (italic or plain)
  // Matches: *This document was generated by Iroko AI...* or plain text version
  cleaned = cleaned.replace(
    /\n*\*?This document was generated by Iroko AI[\s\S]*?(?:before signing or relying on it\.?)\*?\s*$/i,
    '',
  )

  // Remove trailing horizontal rule separator (---) that precedes the disclaimer
  cleaned = cleaned.replace(/\n---\s*$/, '')

  return cleaned.trimEnd()
}

/* ------------------------------------------------------------------ */
/*  Markdown → docx Paragraph[] builder                                */
/* ------------------------------------------------------------------ */

/** Parse a single line's inline bold/italic markup into TextRun[]. */
function parseInlineRuns(line: string): TextRun[] {
  const runs: TextRun[] = []
  // Split on bold (**…**) and italic (*…*) patterns, keeping delimiters.
  const parts = line.split(/(\*\*.*?\*\*|\*.*?\*)/g)
  for (const part of parts) {
    if (!part) continue
    if (part.startsWith('**') && part.endsWith('**')) {
      runs.push(new TextRun({ text: part.slice(2, -2), bold: true }))
    } else if (part.startsWith('*') && part.endsWith('*')) {
      runs.push(new TextRun({ text: part.slice(1, -1), italic: true }))
    } else {
      runs.push(new TextRun({ text: part }))
    }
  }
  return runs
}

/** Convert a Markdown string into an array of docx Paragraphs. */
function markdownToParagraphs(text: string): Paragraph[] {
  const lines = text.split('\n')
  const children: Paragraph[] = []

  for (const rawLine of lines) {
    const line = rawLine.trimEnd()

    // Empty line → spacer
    if (!line.trim()) {
      children.push(new Paragraph({ text: '' }))
      continue
    }

    // Horizontal rule (---, ___, ***)
    if (/^(-{3,}|_{3,}|\*{3,})$/.test(line.trim())) {
      children.push(
        new Paragraph({
          spacing: { before: 120, after: 120 },
          border: {
            bottom: {
              style: BorderStyle.SINGLE,
              size: 6,
              color: '999999',
              space: 1,
            },
          },
        }),
      )
      continue
    }

    // Heading 1
    if (line.startsWith('# ')) {
      children.push(
        new Paragraph({
          children: [
            new TextRun({
              text: line.slice(2).replace(/[*_#]/g, '').toUpperCase(),
              bold: true,
              size: 32, // 16pt
              font: 'Georgia',
            }),
          ],
          heading: HeadingLevel.HEADING_1,
          alignment: AlignmentType.CENTER,
          spacing: { before: 360, after: 240 },
        }),
      )
      continue
    }

    // Heading 2
    if (line.startsWith('## ')) {
      children.push(
        new Paragraph({
          children: [
            new TextRun({
              text: line.slice(3).replace(/[*_#]/g, ''),
              bold: true,
              size: 26, // 13pt
              font: 'Georgia',
              underline: { type: UnderlineType.SINGLE },
            }),
          ],
          heading: HeadingLevel.HEADING_2,
          spacing: { before: 240, after: 120 },
        }),
      )
      continue
    }

    // Heading 3
    if (line.startsWith('### ')) {
      children.push(
        new Paragraph({
          children: [
            new TextRun({
              text: line.slice(4).replace(/[*_#]/g, ''),
              bold: true,
              size: 24, // 12pt
              font: 'Georgia',
            }),
          ],
          heading: HeadingLevel.HEADING_3,
          spacing: { before: 180, after: 90 },
        }),
      )
      continue
    }

    // Bullet list items (- item or * item)
    if (/^\s*[-*]\s+/.test(line)) {
      const content = line.replace(/^\s*[-*]\s+/, '')
      children.push(
        new Paragraph({
          children: parseInlineRuns(content),
          bullet: { level: 0 },
          spacing: { after: 60, line: 276 },
        }),
      )
      continue
    }

    // Numbered list items (1. item)
    if (/^\s*\d+\.\s+/.test(line)) {
      const content = line.replace(/^\s*\d+\.\s+/, '')
      children.push(
        new Paragraph({
          children: parseInlineRuns(content),
          numbering: { reference: 'iroko-numbering', level: 0 },
          spacing: { after: 60, line: 276 },
        }),
      )
      continue
    }

    // Signature underlines (_____)
    if (/^_{3,}/.test(line.trim())) {
      children.push(
        new Paragraph({
          children: [
            new TextRun({
              text: '___________________________',
              font: 'Georgia',
            }),
          ],
          spacing: { before: 240, after: 60 },
        }),
      )
      continue
    }

    // Normal paragraph
    children.push(
      new Paragraph({
        children: parseInlineRuns(line),
        alignment: AlignmentType.JUSTIFY,
        spacing: { after: 120, line: 276 },
      }),
    )
  }

  return children
}

/* ------------------------------------------------------------------ */
/*  Download as native .docx  (client-side Packer, server fallback)    */
/* ------------------------------------------------------------------ */

/** Download document as TRUE native Microsoft Word (.docx) file. */
export async function downloadAsWord(
  rawText: string,
  title?: string,
): Promise<void> {
  // Strip disclaimer before export — it's visible in chat but not in the file
  const text = stripDisclaimerForExport(rawText)
  const docTitle = title || extractDocTitle(text)
  const filename = docTitle
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '_')
    .replace(/^_|_$/g, '')

  try {
    // Client-side generation using docx Packer
    const paragraphs = markdownToParagraphs(text)
    const doc = new Document({
      numbering: {
        config: [
          {
            reference: 'iroko-numbering',
            levels: [
              {
                level: 0,
                format: 'decimal' as any,
                text: '%1.',
                alignment: AlignmentType.START,
              },
            ],
          },
        ],
      },
      sections: [
        {
          properties: {
            page: {
              margin: {
                top: 1440,    // 1 inch in DXA
                right: 1440,
                bottom: 1440,
                left: 1440,
              },
            },
          },
          children: paragraphs,
        },
      ],
    })

    const blob = await Packer.toBlob(doc)
    triggerDownload(blob, `${filename}.docx`)
  } catch (clientErr) {
    console.warn(
      '[downloadAsWord] Client-side Packer failed, falling back to server:',
      clientErr,
    )

    // Server-side fallback
    try {
      const res = await fetch('/api/generate-document/docx', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ text, title: docTitle }),
      })
      if (!res.ok) throw new Error(`Server returned ${res.status}`)
      const blob = await res.blob()
      triggerDownload(blob, `${filename}.docx`)
    } catch (serverErr) {
      console.error('[downloadAsWord] Server fallback also failed:', serverErr)
    }
  }
}

/* ------------------------------------------------------------------ */
/*  Download as PDF  (browser print engine)                            */
/* ------------------------------------------------------------------ */

/** Convert Markdown plain text into clean HTML body for PDF rendering. */
function markdownToHtml(markdown: string): string {
  let html = markdown
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    // Headings
    .replace(
      /^### (.*$)/gim,
      '<h3 style="font-size:13pt;font-weight:bold;margin-top:16px;margin-bottom:8px;color:#111827;">$1</h3>',
    )
    .replace(
      /^## (.*$)/gim,
      '<h2 style="font-size:15pt;font-weight:bold;margin-top:20px;margin-bottom:10px;color:#0f8a5f;border-bottom:1px solid #e5e7eb;padding-bottom:4px;">$1</h2>',
    )
    .replace(
      /^# (.*$)/gim,
      '<h1 style="font-size:18pt;font-weight:bold;text-align:center;margin-bottom:24px;color:#111827;text-transform:uppercase;">$1</h1>',
    )
    // Bold / Italic
    .replace(/\*\*(.*?)\*\*/g, '<strong>$1</strong>')
    .replace(/\*(.*?)\*/g, '<em>$1</em>')
    // Horizontal Rule
    .replace(
      /^---$/gim,
      '<hr style="border:none;border-top:1px solid #d1d5db;margin:24px 0;"/>',
    )
    // Paragraphs
    .replace(
      /\n\n/g,
      '</p><p style="margin-bottom:12px;line-height:1.6;text-align:justify;color:#1f2937;">',
    )
    .replace(/\n/g, '<br/>')

  return `<p style="margin-bottom:12px;line-height:1.6;text-align:justify;color:#1f2937;">${html}</p>`
}

/** Print or Download document as PDF. */
export function downloadAsPdf(rawText: string, title?: string): void {
  // Strip disclaimer before export — it's visible in chat but not in the file
  const text = stripDisclaimerForExport(rawText)
  const docTitle = title || extractDocTitle(text)
  const bodyHtml = markdownToHtml(text)

  const printWindow = window.open('', '_blank', 'width=800,height=900')
  if (!printWindow) return

  printWindow.document.write(`<!DOCTYPE html>
<html>
<head>
  <title>${docTitle}</title>
  <style>
    @page { size: A4; margin: 20mm; }
    body { font-family: 'Georgia', 'Times New Roman', serif; font-size: 11pt; color: #111827; line-height: 1.6; padding: 20px; }
    h1 { font-size: 18pt; text-align: center; text-transform: uppercase; font-weight: bold; margin-bottom: 24px; color: #000; }
    h2 { font-size: 14pt; font-weight: bold; color: #0f8a5f; margin-top: 20px; margin-bottom: 8px; border-bottom: 1px solid #ddd; padding-bottom: 4px; }
    h3 { font-size: 12pt; font-weight: bold; margin-top: 14px; margin-bottom: 6px; }
    p  { text-align: justify; text-justify: inter-word; margin-bottom: 12px; }
    strong { font-weight: bold; }
    em { font-style: italic; }
    @media print { body { padding: 0; } }
  </style>
</head>
<body>
  ${bodyHtml}
  <script>window.onload = function() { window.print(); };<\/script>
</body>
</html>`)
  printWindow.document.close()
}

/* ------------------------------------------------------------------ */
/*  Helpers                                                            */
/* ------------------------------------------------------------------ */

/** Trigger a browser download from a Blob. */
function triggerDownload(blob: Blob, filename: string): void {
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = filename
  document.body.appendChild(a)
  a.click()
  document.body.removeChild(a)
  URL.revokeObjectURL(url)
}
