/**
 * Nigerian legal/business document templates for the Iroko AI document generator.
 * Each template declares the fields to collect; the AI then drafts a complete,
 * Nigerian-law-aware document from the user's inputs.
 */

export type FieldKind = 'text' | 'textarea' | 'number' | 'date' | 'select' | 'money'

export interface DocField {
  id: string
  label: string
  kind: FieldKind
  placeholder?: string
  required?: boolean
  options?: string[]
  help?: string
  /** default value */
  default?: string
}

export interface DocTemplate {
  id: string
  name: string
  description: string
  icon: string
  category: 'legal' | 'business' | 'finance'
  fields: DocField[]
  /** guidance appended to the AI prompt specific to this doc */
  draftingNotes: string
}

/**
 * Legal disclaimer appended to every AI-generated document.
 * Addresses unauthorized-practice-of-law risk under the Legal Practitioners Act:
 * AI output is framed as self-help templates, not legal advice.
 */
export const LEGAL_DISCLAIMER =
  'This document was generated by Iroko AI as a self-help template based on the information you provided. ' +
  'It does not constitute legal advice, and no attorney-client relationship is created. ' +
  'Templates are designed under the supervision of Nigerian legal practitioners. ' +
  'Please have this document reviewed by a qualified lawyer before signing or relying on it.'

export const DOC_TEMPLATES: DocTemplate[] = [
  {
    id: 'tenancy',
    name: 'Tenancy Agreement',
    description: 'Residential tenancy agreement under Nigerian law (Lagos-style).',
    icon: 'Home',
    category: 'legal',
    draftingNotes:
      'Draft a residential tenancy agreement compliant with the Recovery of Premises Act and Lagos State tenancy law. ' +
      'Include parties, property description, term, rent (in ₦), payment terms, duties of both parties, ' +
      'notice to quit (statutory 6 months for monthly/quarterly, or as agreed), dispute resolution, and signature blocks. ' +
      'Add a clause that the tenant must not use the premises for illegal purposes and that the landlord must keep the structure sound.',
    fields: [
      { id: 'landlord', label: 'Landlord full name & address', kind: 'text', placeholder: 'Chief Ade Okafor, 12 Allen Ave, Ikeja', required: true },
      { id: 'tenant', label: 'Tenant full name & address', kind: 'text', placeholder: 'Ngozi Eze, c/o the premises', required: true },
      { id: 'property', label: 'Property address', kind: 'text', placeholder: 'Flat 4, 5 Adeniyi Jones, Ikeja, Lagos', required: true },
      { id: 'term', label: 'Tenancy term', kind: 'select', options: ['1 year', '2 years', '6 months', '3 months'], default: '1 year', required: true },
      { id: 'rent', label: 'Annual rent (₦)', kind: 'money', placeholder: '1,200,000', required: true },
      { id: 'paymentFreq', label: 'Payment frequency', kind: 'select', options: ['Annually', 'Bi-annually', 'Quarterly', 'Monthly'], default: 'Annually' },
      { id: 'commencement', label: 'Commencement date', kind: 'date' },
      { id: 'deposit', label: 'Security/caution deposit (₦)', kind: 'money', placeholder: '200,000' },
    ],
  },
  {
    id: 'partnership',
    name: 'Partnership Agreement',
    description: 'General partnership agreement between two or more Nigerian partners.',
    icon: 'Handshake',
    category: 'legal',
    draftingNotes:
      'Draft a partnership agreement under the Partnership Law of Nigeria. ' +
      'Include firm name, partners, contributions (capital/in kind), profit/loss sharing, management duties, ' +
      'admission/withdrawal of partners, dissolution, governing law, and signature blocks. ' +
      'Use clear numbered clauses.',
    fields: [
      { id: 'firmName', label: 'Firm name', kind: 'text', placeholder: 'Eze & Sons Enterprises', required: true },
      { id: 'partners', label: 'Partner names & addresses', kind: 'textarea', placeholder: '1. Ngozi Eze, Lekki, Lagos\n2. Tunde Bello, Surulere, Lagos', required: true },
      { id: 'business', label: 'Nature of business', kind: 'text', placeholder: 'General merchandising and logistics', required: true },
      { id: 'capital', label: 'Total capital contributed (₦)', kind: 'money', placeholder: '5,000,000' },
      { id: 'profitSharing', label: 'Profit/loss sharing', kind: 'select', options: ['Equally', 'In proportion to capital', 'As specified below'], default: 'Equally' },
      { id: 'commencement', label: 'Commencement date', kind: 'date' },
    ],
  },
  {
    id: 'employment',
    name: 'Employment Contract',
    description: 'Employment contract compliant with the Nigerian Labour Act.',
    icon: 'Briefcase',
    category: 'legal',
    draftingNotes:
      'Draft an employment contract compliant with the Labour Act (Cap L1, LFN 2004). ' +
      'Include employer, employee, position, probation, remuneration (₦), hours, leave, termination notice ' +
      '(per the Act: 1 day–1 week pay ≤3 months, etc.), confidentiality, and signature blocks.',
    fields: [
      { id: 'employer', label: 'Employer (company) name', kind: 'text', placeholder: 'Iroko Technologies Limited', required: true },
      { id: 'employee', label: 'Employee name & address', kind: 'text', placeholder: 'Chidi Okafor, Yaba, Lagos', required: true },
      { id: 'position', label: 'Job title', kind: 'text', placeholder: 'Operations Manager', required: true },
      { id: 'salary', label: 'Monthly gross salary (₦)', kind: 'money', placeholder: '350,000', required: true },
      { id: 'probation', label: 'Probation period', kind: 'select', options: ['3 months', '6 months', 'None'], default: '3 months' },
      { id: 'commencement', label: 'Start date', kind: 'date' },
      { id: 'leave', label: 'Annual leave (days)', kind: 'number', default: '21' },
    ],
  },
  {
    id: 'invoice',
    name: 'Service Invoice',
    description: 'Professional service invoice with VAT (7.5%) calculated.',
    icon: 'ReceiptText',
    category: 'finance',
    draftingNotes:
      'Generate a clean, professional service invoice. Include seller & buyer, invoice number, date, ' +
      'line items with quantities and unit prices in ₦, subtotal, VAT at 7.5%, and total. ' +
      'Add payment instructions (Nigerian bank transfer) and a thank-you note.',
    fields: [
      { id: 'seller', label: 'Your business name & address', kind: 'text', placeholder: 'Iroko Technologies Ltd, Ikeja, Lagos', required: true },
      { id: 'buyer', label: 'Client name & address', kind: 'text', placeholder: 'Acme Ltd, Victoria Island, Lagos', required: true },
      { id: 'invoiceNo', label: 'Invoice number', kind: 'text', placeholder: 'INV-2024-001', default: 'INV-2024-001', required: true },
      { id: 'date', label: 'Invoice date', kind: 'date' },
      { id: 'items', label: 'Line items (description — qty × unit price ₦)', kind: 'textarea', placeholder: 'Web design — 1 × 450000\nHosting (1yr) — 1 × 80000', required: true },
    ],
  },
  {
    id: 'memorandum',
    name: 'Company Memorandum (preview)',
    description: 'Preview CAC Memorandum of Association for an LLC under CAMA 2020.',
    icon: 'FileText',
    category: 'business',
    draftingNotes:
      'Draft a CAC-style Memorandum of Association for a private company limited by shares under CAMA 2020. ' +
      'Include the company name clause, registered office (Lagos/Abuja/etc.), objects clause, ' +
      'share capital (minimum ₦100,000 authorised for LLC), subscribers, and their shares. ' +
      'Mark clearly this is a draft preview to be confirmed by a legal agent.',
    fields: [
      { id: 'companyName', label: 'Company name (with Ltd)', kind: 'text', placeholder: 'Iroko Technologies Limited', required: true },
      { id: 'office', label: 'Registered office (state)', kind: 'text', placeholder: 'Ikeja, Lagos State', required: true },
      { id: 'objects', label: 'Main business objects', kind: 'textarea', placeholder: 'To carry on the business of technology services, software development and consulting.', required: true },
      { id: 'capital', label: 'Authorised share capital (₦)', kind: 'money', placeholder: '1,000,000', default: '1,000,000', required: true },
      { id: 'subscribers', label: 'Subscribers (name, address, shares)', kind: 'textarea', placeholder: '1. Ngozi Eze, Lagos — 500,000 shares\n2. Tunde Bello, Lagos — 500,000 shares', required: true },
    ],
  },
  {
    id: 'nda',
    name: 'Non-Disclosure Agreement (NDA)',
    description: 'Mutual or One-Way Non-Disclosure and Confidentiality Agreement under Nigerian law.',
    icon: 'Lock',
    category: 'legal',
    draftingNotes:
      'Draft a Non-Disclosure Agreement (NDA) compliant with Nigerian commercial contract law and the Nigeria Data Protection Act (NDPA) 2023. ' +
      'Include disclosing party, receiving party, purpose of disclosure, definition of confidential information, ' +
      'exclusions, duration of confidentiality (typically 2-5 years), remedies for breach, governing law (Courts of Nigeria), and execution signature blocks.',
    fields: [
      { id: 'disclosingParty', label: 'Disclosing Party name & address', kind: 'text', placeholder: 'Iroko AI Tech Ltd, Ikeja, Lagos', required: true },
      { id: 'receivingParty', label: 'Receiving Party name & address', kind: 'text', placeholder: 'Apex Ventures Nigeria, Victoria Island, Lagos', required: true },
      { id: 'ndaType', label: 'Agreement Type', kind: 'select', options: ['Mutual (Two-way)', 'One-Way'], default: 'Mutual (Two-way)' },
      { id: 'purpose', label: 'Purpose of disclosure', kind: 'textarea', placeholder: 'Exploration of potential strategic partnership and software integration', required: true },
      { id: 'duration', label: 'Confidentiality period', kind: 'select', options: ['2 years', '3 years', '5 years', 'Perpetual'], default: '3 years' },
    ],
  },
  {
    id: 'powerOfAttorney',
    name: 'Power of Attorney',
    description: 'General or Special Power of Attorney for property, CAC, or administrative representation in Nigeria.',
    icon: 'Scale',
    category: 'legal',
    draftingNotes:
      'Draft a formal Power of Attorney instrument under Nigerian property and agency law. ' +
      'Include Donor (principal), Donee (attorney-in-fact), specific powers conferred (e.g. CAC registration, land administration, court appearance), ' +
      'revocability, date of execution, and witness signature blocks under seal.',
    fields: [
      { id: 'donor', label: 'Donor (Principal) full name & address', kind: 'text', placeholder: 'Chief Emeka Okonkwo, Ikoyi, Lagos', required: true },
      { id: 'donee', label: 'Donee (Attorney) full name & address', kind: 'text', placeholder: 'Barr. Folake Adeleke, Ikeja, Lagos', required: true },
      { id: 'poaScope', label: 'Scope of Powers', kind: 'textarea', placeholder: 'To represent the Donor before the Corporate Affairs Commission (CAC) and sign incorporation documents on Donor behalf.', required: true },
      { id: 'effectiveDate', label: 'Effective Date', kind: 'date' },
    ],
  },
  {
    id: 'boardResolution',
    name: 'Board Resolution',
    description: 'Formal company board resolution for corporate bank account opening or director authorization.',
    icon: 'Building',
    category: 'business',
    draftingNotes:
      'Draft a formal Board Resolution under CAMA 2020. ' +
      'Include company name, RC number, date of meeting, directors present, specific resolutions passed (e.g., opening a bank account with Access Bank/GTBank, authorized signatories), ' +
      'and signatures of the Director and Company Secretary.',
    fields: [
      { id: 'companyName', label: 'Company name & RC Number', kind: 'text', placeholder: 'Zeta Synergy Ltd (RC: 1234567)', required: true },
      { id: 'resolutionTitle', label: 'Resolution Subject', kind: 'text', placeholder: 'Opening of Corporate Bank Account & Mandate Approval', required: true },
      { id: 'bankName', label: 'Bank Name & Branch (if applicable)', kind: 'text', placeholder: 'Guaranty Trust Bank (GTBank), Lekki Branch' },
      { id: 'signatories', label: 'Authorized Signatories & Mandate (Category A/B)', kind: 'textarea', placeholder: '1. Mr. Tunde Bakare (Managing Director) - Category A\n2. Mrs. Chioma Nnadi (Director) - Category B', required: true },
      { id: 'meetingDate', label: 'Date of Board Meeting', kind: 'date' },
    ],
  },
]

export function getDocTemplate(id: string): DocTemplate | undefined {
  return DOC_TEMPLATES.find((t) => t.id === id)
}

/**
 * Build the prompt sent to the AI to generate the document.
 * Returns the user message; the server appends the Iroko system prompt.
 */
export function buildDocGenerationPrompt(template: DocTemplate, values: Record<string, string>): string {
  const filled = template.fields
    .map((f) => {
      const v = (values[f.id] || '').trim()
      return `- ${f.label}: ${v || '(not provided)'}`
    })
    .join('\n')

  return [
    `Please draft a complete ${template.name} for me. Use the details below.`,
    ``,
    `Details provided:`,
    filled,
    ``,
    `Drafting guidance:`,
    template.draftingNotes,
    ``,
    `CRITICAL RULES:`,
    `1. Use ALL the real values provided above. NEVER use placeholder brackets like [Name], [Date], [Address]. Every field must be filled with the actual value. The document must be READY TO PRINT AND SEND.`,
    `2. If a field says "(not provided)", use a reasonable default or today's date (${new Date().toLocaleDateString('en-GB', { day: 'numeric', month: 'long', year: 'numeric' })}).`,
    `3. Format the document in clean Markdown with a level-1 heading in ALL CAPS, numbered clauses/sections, and signature blocks using the REAL party names.`,
    `4. After the signature block, add a "---" horizontal rule, then on the next line put this disclaimer in italics:`,
    ``,
    `*${LEGAL_DISCLAIMER}*`,
  ].join('\n')
}
