/**
 * Per-service task handlers — what actually happens once a task is paid.
 *
 * Routing by catalog tier:
 *  - 'ai'     → delivered instantly by the LLM (e.g. contract drafting).
 *  - 'online' → try portal automation; if the automation layer isn't
 *               available/enabled, escalate to NEEDS_HUMAN with a
 *               filing-ready submission pack for the back-office.
 *  - 'agent'  → NEEDS_HUMAN immediately with an agent-dispatch pack
 *               (physical presence is required by the process itself).
 */

import { AGENT_SERVICES, type AgentService } from './iroko-services'
import { PORTAL_INFO, runPortalAutomation } from './portal-automation'
import { completeChat } from './llm'
import type { TaskHandler, TaskHandlerContext, TaskHandlerOutcome } from './task-engine'

function getService(serviceId: string): AgentService | undefined {
  return AGENT_SERVICES.find((s) => s.id === serviceId)
}

function detailsTable(details: Record<string, string>): string {
  const rows = Object.entries(details)
  if (rows.length === 0) return '_No details collected._'
  return rows.map(([k, v]) => `| ${k} | ${v} |`).join('\n')
}

/**
 * A deterministic, filing-ready markdown pack: everything a back-office
 * operator (or later, a stationed agent) needs to complete the task by hand.
 * Deliberately template-based — no LLM tokens spent in the background.
 */
function buildSubmissionPack(service: AgentService, details: Record<string, string>): string {
  const portal = service.portal ? PORTAL_INFO[service.portal] : null
  return [
    `# Submission pack — ${service.name}`,
    ``,
    `**Tier:** ${service.layer}${portal ? ` · **Portal:** [${portal.name}](${portal.url})` : ''}`,
    `**Typical duration:** ${service.duration}`,
    service.officialFee ? `**Official fee:** ${service.officialFee}` : '',
    ``,
    `## Details collected from the user`,
    `| Field | Value |`,
    `| --- | --- |`,
    detailsTable(details),
    ``,
    `## Checklist (from the service requirements)`,
    ...service.requirements.map((r) => `- [ ] ${r}`),
    ``,
    `## Operator notes`,
    portal
      ? `Complete this filing on the ${portal.name} (${portal.url}) using the back-office account, then attach the receipt/certificate to this task and mark it COMPLETED.`
      : `Dispatch to the nearest available agent for this service type; the agent completes the physical step and uploads proof.`,
  ]
    .filter(Boolean)
    .join('\n')
}

/** 'online' tier: automation first, clean human escalation second. */
const onlineHandler: TaskHandler = async (ctx: TaskHandlerContext): Promise<TaskHandlerOutcome> => {
  const service = getService(ctx.serviceId)
  if (!service) throw new Error(`Unknown service: ${ctx.serviceId}`)

  if (service.portal) {
    const result = await runPortalAutomation(ctx.serviceId, service.portal, ctx.details, ctx.log)
    if (result.ok) {
      return {
        status: 'COMPLETED',
        note: `Completed automatically on the ${PORTAL_INFO[service.portal].name}.`,
        result: { via: 'portal-automation', ...result.artifacts },
      }
    }
    await ctx.log(`Automation unavailable: ${result.note}`)
  }

  return {
    status: 'NEEDS_HUMAN',
    note: 'Queued for the Iroko back-office to complete on the government portal. You will be updated here.',
    result: { via: 'back-office', submissionPack: buildSubmissionPack(service, ctx.details) },
  }
}

/** 'agent' tier: physical presence required — prepare the dispatch pack. */
const agentHandler: TaskHandler = async (ctx): Promise<TaskHandlerOutcome> => {
  const service = getService(ctx.serviceId)
  if (!service) throw new Error(`Unknown service: ${ctx.serviceId}`)
  return {
    status: 'NEEDS_HUMAN',
    note: 'An Iroko agent stationed at the relevant office will be assigned to this request. Track progress here.',
    result: { via: 'agent-network', submissionPack: buildSubmissionPack(service, ctx.details) },
  }
}

/** 'ai' tier (contract drafting): the LLM does the work, delivered on the task. */
const contractDraftHandler: TaskHandler = async (ctx): Promise<TaskHandlerOutcome> => {
  const detailLines = Object.entries(ctx.details)
    .map(([k, v]) => `- ${k}: ${v}`)
    .join('\n')
  const document = await completeChat({
    messages: [
      {
        role: 'system',
        content:
          'You are Iroko AI, drafting Nigerian-law-compliant legal documents. Output ONLY the complete document in clean Markdown: title, numbered clauses, ₦ for amounts, signature blocks. End with a one-line footer that it was generated by Iroko AI and should be reviewed by a legal professional before signing.',
      },
      {
        role: 'user',
        content: `Draft the contract described below.\n\nDetails:\n${detailLines || '(none provided — draft a sensible general template and mark blanks clearly)'}`,
      },
    ],
    temperature: 0.3,
    maxTokens: 4000,
  })
  return {
    status: 'COMPLETED',
    note: 'Contract drafted by Iroko AI — ask me to show it, or find it on the task.',
    result: { via: 'ai', document },
  }
}

const SPECIAL_HANDLERS: Record<string, TaskHandler> = {
  'contract-draft': contractDraftHandler,
}

export function getTaskHandler(serviceId: string): TaskHandler {
  const special = SPECIAL_HANDLERS[serviceId]
  if (special) return special
  const service = getService(serviceId)
  if (!service) {
    return async () => {
      throw new Error(`Unknown service: ${serviceId}`)
    }
  }
  return service.layer === 'online' ? onlineHandler : agentHandler
}
